### ISSUE TITLE
hideStatusBar not working

### ISSUE THREAD

**Issue by allaire** [JanGorman/Agrume#72]
I see there is a `hideStatusBar`, but from my side, it seems like it's not working, since the status bar is still present. Anything I am missing?

```
            let agrume = Agrume(image: image, backgroundBlurStyle: .dark)
            agrume.hideStatusBar = true
            agrume.showFrom(topViewController)
```

**Comment by JanGorman** [comment]
Hi,
this should be working, I tried the sample code just to be sure and this is the result I get:
<img width="320" alt="screen shot 2018-01-03 at 20 51 02" src="https://user-images.githubusercontent.com/138166/34537190-f51378aa-f0c7-11e7-8bd9-5dea5d69432c.png">

in your case, what is `topViewController`? I suspect your issue has something to do with that

**Comment by allaire** [comment]
@JanGorman Thanks for getting back so quickly!

I'm calling Agrume in a custom handler class, so I'm using a custom class method to find the top view controller:

```
    class func topViewController(baseViewController: UIViewController? = UIApplication.shared.keyWindow?.rootViewController) -> UIViewController? {
        if let navigationController = baseViewController as? UINavigationController {
            return topViewController(baseViewController: navigationController.visibleViewController)
        }
        
        if let tabBarController = baseViewController as? UITabBarController {
            if let selectedViewController = tabBarController.selectedViewController {
                return topViewController(baseViewController: selectedViewController)
            }
        }
        
        if let presentedViewController = baseViewController?.presentedViewController {
            return topViewController(baseViewController: presentedViewController)
        }
        
        return baseViewController
    }
```

**Comment by JanGorman** [comment]
Thanks for sharing – I tried a sample with your code but it still hides the status bar just fine so I'll need to dig a bit deeper. In theory "manually" finding from where to present should not not be needed though.

The library actually does something similar to find out which view to screenshot and then blur: https://github.com/JanGorman/Agrume/blob/0a1d7bbdfa4aff2bbe79ea8b400fd7dc5503cc7c/Agrume/Agrume.swift#L287 

Also see https://github.com/JanGorman/Agrume/pull/26 for some background (🥁) information.

In the meantime, can you let me know what happens when you change your way to find the topVC with what Agrume is doing to get the screenshot, i.e.

```swift
  class func topViewController(baseViewController: UIViewController? = UIApplication.shared.keyWindow?.rootViewController) -> UIViewController? {
    var presentingVC = baseViewController?.view.window?.rootViewController
    while presentingVC?.presentedViewController != nil {
      presentingVC = presentingVC?.presentedViewController
    }
    return presentingVC
  }
```

**Comment by allaire** [comment]
@JanGorman I tried with your code and it's still not working.

I'm in a UINavigationController inside a UITabBarController if it helps

**Comment by JanGorman** [comment]
@allaire Thanks for the additional info. I'll see if I can replicate it that way.

**Comment by JanGorman** [comment]
@allaire I think I still need a little more context. What I tried was this: On the sample project that's part of this repository I embedded the root navigation controller in a tab bar controller:

![screen shot 2018-01-04 at 10 45 33](https://user-images.githubusercontent.com/138166/34557982-699f5d6e-f13c-11e7-9dd0-46aa144c7063.png)

And then in the `SingleImageViewController` class added your code to find the top VC and modified the existing code like this:

```swift
  override func viewDidLoad() {
    super.viewDidLoad()
    agrume = Agrume(image: #imageLiteral(resourceName: "MapleBacon"), backgroundBlurStyle: .dark)
    agrume.hideStatusBar = true
  }

  @IBAction func openImage(_ sender: Any) {
//    agrume.showFrom(self)
    if let top = topViewController() {
      agrume.showFrom(top)
    }
  }
```

This works fine (as does the regular call to `agrume.showFrom(self)`). Any ideas what could be different to your specific case?

**Comment by allaire** [comment]
@JanGorman Finally found why! My project has in the Info.plist the property `View controller-based status bar appearance` set to NO. That's why it's ignoring the setting.

I don't think there's a way to hide the status bar when this setting is set to NO.

Thanks!

**Comment by JanGorman** [comment]
😅 yes, that makes sense. Glad to hear you found a solution
